/**
 * Feed metrics — measure feed value and engagement.
 * Tracks whether the feed is earning its price.
 */

import type { FeedTier, FeedSignalType, MixedInsight, FeedStatus } from "./types.js";

export interface FeedMetrics {
  /** Total feed items received since startup. */
  itemsReceived: number;
  /** Items by signal type. */
  itemsByType: Partial<Record<FeedSignalType, number>>;
  /** Total insights generated by the mixing engine. */
  insightsGenerated: number;
  /** Insights that were surfaced to the user (injected into context). */
  insightsSurfaced: number;
  /** Average relevance score of generated insights. */
  avgRelevance: number;
  /** Feed uptime ratio (connected time / total time). */
  uptimeRatio: number;
  /** Current tier. */
  tier: FeedTier;
  /** Timestamp of first item received. */
  firstItemAt: string | null;
  /** Timestamp of most recent item. */
  lastItemAt: string | null;
}

export class FeedMetricsCollector {
  private itemsReceived = 0;
  private itemsByType: Partial<Record<FeedSignalType, number>> = {};
  private insightsGenerated = 0;
  private insightsSurfaced = 0;
  private relevanceSum = 0;
  private connectedMs = 0;
  private totalMs = 0;
  private lastTickAt: number = Date.now();
  private connected = false;
  private tier: FeedTier;
  private firstItemAt: string | null = null;
  private lastItemAt: string | null = null;

  constructor(tier: FeedTier) {
    this.tier = tier;
  }

  /** Call periodically (or before reading metrics) to update uptime tracking. */
  tick(): void {
    const now = Date.now();
    const elapsed = now - this.lastTickAt;
    this.totalMs += elapsed;
    if (this.connected) {
      this.connectedMs += elapsed;
    }
    this.lastTickAt = now;
  }

  recordItemsReceived(count: number, types: FeedSignalType[]): void {
    this.itemsReceived += count;
    const now = new Date().toISOString();
    if (!this.firstItemAt) this.firstItemAt = now;
    this.lastItemAt = now;
    for (const t of types) {
      this.itemsByType[t] = (this.itemsByType[t] ?? 0) + 1;
    }
  }

  recordInsights(insights: MixedInsight[]): void {
    this.insightsGenerated += insights.length;
    for (const i of insights) {
      this.relevanceSum += i.relevance;
    }
  }

  recordInsightSurfaced(): void {
    this.insightsSurfaced++;
  }

  setConnected(connected: boolean): void {
    this.tick();
    this.connected = connected;
  }

  setTier(tier: FeedTier): void {
    this.tier = tier;
  }

  getMetrics(): FeedMetrics {
    this.tick();
    return {
      itemsReceived: this.itemsReceived,
      itemsByType: { ...this.itemsByType },
      insightsGenerated: this.insightsGenerated,
      insightsSurfaced: this.insightsSurfaced,
      avgRelevance: this.insightsGenerated > 0 ? this.relevanceSum / this.insightsGenerated : 0,
      uptimeRatio: this.totalMs > 0 ? this.connectedMs / this.totalMs : 0,
      tier: this.tier,
      firstItemAt: this.firstItemAt,
      lastItemAt: this.lastItemAt,
    };
  }

  /** Snapshot for feed status reporting. */
  toFeedStatus(cachedItems: number): FeedStatus {
    this.tick();
    return {
      connected: this.connected,
      tier: this.tier,
      lastReceivedAt: this.lastItemAt,
      itemsCached: cachedItems,
      insightsGenerated: this.insightsGenerated,
      avgRelevance: this.insightsGenerated > 0 ? this.relevanceSum / this.insightsGenerated : 0,
    };
  }
}
